name: Run birthday bot

on:
  schedule:
    - '0 14 * * *'  # every day at 2:00pm

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Set up runtime environment
        run: |
          python -m venv venv
          source ./venv/scripts/activate
          pip install -r requirements.txt

      - name: Run bot
        run: python main.py
