name: Run birthday bot

on:
  schedule:
    - cron: '0 14 * * *'  # every day at 2:00pm
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Set up runtime environment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: pytest

      - name: Run bot
        run: python main.py
        env:
          BOT_TOKEN: '${{ secrets.BOT_TOKEN }}'
          CHANNEL_ID: '${{ secrets.CHANNEL_ID }}'
